name: Deploy Monitoring Stack

on:
  push:
    paths:
      - 'monitoring/**'
      - 'docker-compose.yml'

jobs:
  deploy-monitoring:
    name: Deploy Prometheus and Grafana to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Ir al repositorio
          cd ~/tallervv || {
            echo "Clonando repositorio por primera vez..."
            git clone https://github.com/veronicaalarcona/tallervv.git ~/tallervv
            cd ~/tallervv
          }

          # Actualizar código
          git pull origin main

          # 🔥 Eliminar conflicto: directorio con el nombre del archivo
          if [ -d monitoring/prometheus/prometheus.yml ]; then
            echo "Eliminando directorio prometheus.yml que causa conflicto..."
            sudo rm -rf monitoring/prometheus/prometheus.yml
          fi

          # ✅ Verificar si el archivo existe después del pull
          if [ ! -f monitoring/prometheus/prometheus.yml ]; then
            echo "Archivo prometheus.yml no existe, creando uno por seguridad..."
            mkdir -p monitoring/prometheus
            cat > monitoring/prometheus/prometheus.yml << 'EOF'
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
EOF
          fi

          # 🔄 Levantar contenedores con Docker Compose
          docker-compose down -v
          docker-compose up -d prometheus grafana
